### ISSUE TITLE
python脚本执行错误，导入模块错误

### ISSUE THREAD

**Issue by seemebb** [Huawei/OpenStackClient_KMS#1]
**按照python脚本调用方法，编写python脚本运行，出现模块导入错误。**

root@CTU1000028712:/kms-plugin-test# cat kms_plugin.py 
from keystoneauth1 import session
from keystoneauth1 import client
from kmclient.v1 import client
auth = identity.v3.Password(auth_url=u'xxxx',
                             username=u'xxxx',
                             user_domain_id=u'xxxx',
                             password=u'xxxx',
                             project_name=u'xxxx',
                             project_domain_name=u'xxxx')						 
session = session.Session(auth=auth)
client = client.Client(session=session)
client.keys.get('key-id-1')

root@CTU1000028712:/kms-plugin-test# python kms_plugin.py 
Traceback (most recent call last):
  File "kms_plugin.py", line 2, in <module>
    from keystoneauth1 import client
ImportError: cannot import name client

**已经确认keystoneauth1模块已安装，但模块下找不到client.py，请问下需要怎么解决？**

**Comment by IamFive** [comment]
稍等 我看一下。

**Comment by IamFive** [comment]
文档上引入的有误，已修订。
