### ISSUE TITLE
policy、usage、type为扩展字段，以后才会使用，当前文档不引导填写

### ISSUE THREAD

**Issue by seemebb** [Huawei/OpenStackClient_KMS#10]
policy、usage、type为扩展字段，以后才会使用，当前文档不引导填写

参考文档优化

当前文档：
$ openstack kms key create qianbiao-ng --realm eu-de --description desc
    --policy '{"key":"value"}' --usage usage --type keytype
    --sequence 919c82d4-8046-4722-9094-35c3c6524cff

文档修改为：
$ openstack kms key create qianbiao-ng --realm eu-de --description desc
    --sequence 919c82d4-8046-4722-9094-35c3c6524cff

**Comment by IamFive** [comment]
Fixed
