### ISSUE TITLE
有个问题请教下，加密数据密钥接口 中的参数 plain_text 是怎么来的，DEK的plain-text是128位，不是64位。

### ISSUE THREAD

**Issue by seemebb** [Huawei/OpenStackClient_KMS#11]
文档里面对plain_text描述很清楚，明文是64字节的数据（即512bit）加上它的sha256。且为16进制表示的。 128/2=64。两个位数对应一个字节。

16进制表示：例如数据"a"，1个字节的数据，对应的16进制字符串表示为“61“

**Comment by IamFive** [comment]
这个 plain-text 是 `创建数据密钥` 这个接口那边返回的 plain-text + sha256(plain-text) ?

我用这个提交，结果告诉我 hash验证不通过。
