### ISSUE TITLE
命令行风格不符合要求，参数命名需与文档保持一致

### ISSUE THREAD

**Issue by seemebb** [Huawei/OpenStackClient_KMS#3]
**命令行风格需要保持一致，例如：openstack kms + 接口名称 + 接口参数**
**参数命名需与接口文档保持一致，并支持可选参数**

**12个接口预期如下：**
r1、预期：openstack kms create-key --key-alias keyalias --realm eu-de --key-description desc --key-policy policy --key-usage usage --key-type keytype --sequence 919c82d4-8046-4722-9094-35c3c6524cff 
r1、预期：openstack kms enable-key --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --sequence 919c82d4-8046-4722-9094-35c3c6524cff 
r1、预期：openstack kms disable-key --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --sequence 919c82d4-8046-4722-9094-35c3c6524cff 
r1、预期：openstack kms schedule-key-deletion --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --pending-days 7 --sequence 919c82d4-8046-4722-9094-35c3c6524cff 
r1、预期：openstack kms cancel-key-deletion --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --sequence 919c82d4-8046-4722-9094-35c3c6524cff 
r1、预期：openstack kms list-keys --limit 2 --marker 0 --sequence 919c82d4-8046-4722-9094-35c3c6524cff 
r1、预期：openstack kms describe-key --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --sequence 919c82d4-8046-4722-9094-35c3c6524cff 
r1、预期：openstack kms gen-random --random-data-length 512 --sequence 919c82d4-8046-4722-9094-35c3c6524cff 
r1、预期：openstack kms create-datakey --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --encryption-context context --datakey-length 512 --sequence 919c82d4-8046-4722-9094-35c3c6524cff 
r1、预期：openstack kms create-datakey-without-plaintext --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --encryption-context context --datakey-length 512 --sequence 919c82d4-8046-4722-9094-35c3c6524cff 
r1、预期：openstack kms encrypt-datakey --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --encryption-context context  --plain-text plaintext  --datakey-plain-length 64 --sequence 919c82d4-8046-4722-9094-35c3c6524cff 
r1、预期：openstack kms decrypt-datakey --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --encryption-context context  --cipher-text ciphertext --datakey-cipher-length 64 --sequence 919c82d4-8046-4722-9094-35c3c6524cff

**Comment by IamFive** [comment]
这里面有些不合理，比如：
1.  --datakey-plain-length 64 这种是固定值，为何还要让用户录入
2. --key-policy policy 这种是无效参数，设置不设置没任何区别
3. 命令命名不符合官方习惯，官方习惯是 资源名+资源操作
4.  --encryption-context context 这种并不比 --context=xx=xx --context=xx=xx 好用。

总之，让PM确认下，如果确定要改成这样，我晚点会提交上来。

**Comment by seemebb** [comment]
**和PM确认后的说明：**
1、--datakey-plain-length 参数需要支持，当前只支持64，以后可能会扩展支持其他位数的密钥。
2、--policy policy参数需要支持，扩展字段，以后会用到--policy，policy为json字符串。
3、命令格式参考如下： 
r1、预期：openstack kms key create --alias keyalias --realm eu-de --description desc --policy policy --usage usage --type keytype --sequence 919c82d4-8046-4722-9094-35c3c6524cff
r1、预期：openstack kms key enable --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --sequence 919c82d4-8046-4722-9094-35c3c6524cff
r1、预期：openstack kms key disable --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --sequence 919c82d4-8046-4722-9094-35c3c6524cff
r1、预期：openstack kms key schedule deletion --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --pending-days 7 --sequence 919c82d4-8046-4722-9094-35c3c6524cff
r1、预期：openstack kms key cancel deletion --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --sequence 919c82d4-8046-4722-9094-35c3c6524cff
r1、预期：openstack kms key list --limit 2 --marker 0 --sequence 919c82d4-8046-4722-9094-35c3c6524cff
r1、预期：openstack kms key describe --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --sequence 919c82d4-8046-4722-9094-35c3c6524cff
r1、预期：openstack kms random generate --random-data-length 512 --sequence 919c82d4-8046-4722-9094-35c3c6524cff
r1、预期：openstack kms datakey create --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --encryption-context context --datakey-length 512 --sequence 919c82d4-8046-4722-9094-35c3c6524cff
r1、预期：openstack kms datakey create --without-plain-text --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --encryption-context context --datakey-length 512 --sequence 919c82d4-8046-4722-9094-35c3c6524cff
r1、预期：openstack kms datakey encrypt --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --encryption-context context --plain-text plaintext --datakey-plain-length 64 --sequence 919c82d4-8046-4722-9094-35c3c6524cff
r1、预期：openstack kms datakey decrypt --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --encryption-context context --cipher-text ciphertext --datakey-cipher-length 64 --sequence 919c82d4-8046-4722-9094-35c3c6524cff
4、--encryption-context context 与aws保持一致，使用--encryption-context ，context为json字符串，且值为key-value对。
5、参数已根据建议修改为：--alias keyalias --realm eu-de --description desc --policy policy --usage usage --type keytype

**Comment by IamFive** [comment]
1、--datakey-plain-length 参数需要支持，当前只支持64，以后可能会扩展支持其他位数的密钥。
我这边限制用户输入 整数吗，用户输入撒我就提交撒？假如用户输入不是64呢。

2、--policy policy参数需要支持，扩展字段，以后会用到--policy，policy为json字符串。
json字符串是 key,value吗。--policy=k1=v1,k2=v2？

3. --encryption-context 输入也是 --encryption-context=k1=v1,k2=v2 吗

**Comment by IamFive** [comment]
针对字典类型的数据，Openstack官方插件现在的输入方式是：
输入 `--encryption-context=k1=v1 --encryption-context=k1=v2 `
输出 `{"k1": "v1", "k2": "v2"}`

针对字典列表类型的数据，Openstack官方插件现在的输入方式是：
输入 `--encryption-context=k1=v1,k2=v2 --encryption-context=k3=v4,k4=v4 `
输出 `[{"k1": "v1", "k2": "v2"}, {"k3": "v3", "k4": "v4"}]`

@seemebb

**Comment by seemebb** [comment]
问题确认说明：
1、--datakey-plain-length参数需支持。

2、--policy参数由于输入的json字符串格式不确定，需输入json字符串全部内容.
例如：--policy “{\"name\": \"kms_adm\",\"display_name\": \"KMS Administrator\",\"description\": \"KMS Administrator\",\"catalog\": \"KMS\",\"policy\": {\"Version\": \"1.0\",\"Statement\": [{\"Effect\": \"Allow\",\"Action\": [\"KMS:KMS:*\"]}]}}”

3、--encryption-context 参数为key-value的json字符串，可以按照官方的形式设计：--encryption-context=k1=v1 --encryption-context=k1=v2
例如：{"Key1":"Value1","Key2":"Value2"}  输入为：--encryption-context=Key1=Value1 --encryption-context=Key2=Value2

**Comment by IamFive** [comment]
在针对key各种操作的命令中，--key-id 的参数，现在都是用 action + resource（id or name) 这种方式来的，不会通过 optional 参数来处理。

比如
openstack kms key enable --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f

通常是：

openstack kms key enable 0d0466b0-e727-4d9c-b35d-f84bb474a37f

**Comment by IamFive** [comment]
已处理，请验收

**Comment by seemebb** [comment]
根据建议，保持与openstack官方统一风格，命令调整如下：

创建密钥：
openstack kms key create keyalias --realm eu-de --description desc --policy policy --usage usage --type keytype --sequence 11111111-1111-1111-1111-111111111111
启用密钥：
openstack kms key enable 0d0466b0-e727-4d9c-b35d-f84bb474a37f --sequence 11111111-1111-1111-1111-111111111111
禁用密钥：
openstack kms key disable 0d0466b0-e727-4d9c-b35d-f84bb474a37f --sequence 11111111-1111-1111-1111-111111111111
计划删除密钥：
openstack kms key schedule deletion 0d0466b0-e727-4d9c-b35d-f84bb474a37f --pending-days 7 --sequence 11111111-1111-1111-1111-111111111111
取消计划删除密钥：
openstack kms key cancel deletion 0d0466b0-e727-4d9c-b35d-f84bb474a37f --sequence 11111111-1111-1111-1111-111111111111 
查询密钥列表：
openstack kms key list --limit 2 --offset 0 --sequence=11111111-1111-1111-1111-111111111116
查询密钥信息：
openstack kms key show 978d47a2-838f-48d5-bb9b-4e7f0e1ec49b --sequence 11111111-1111-1111-1111-111111111117 
创建随机数：
openstack kms random generate 512 --sequence 11111111-1111-1111-1111-111111111118
创建数据密钥：
openstack kms datakey create --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --encryption-context context --datakey-length 512 --sequence 11111111-1111-1111-1111-111111111111
创建不含明文数据密钥：
openstack kms datakey create --without-plain-text --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --encryption-context context --datakey-length 512 --sequence 11111111-1111-1111-1111-111111111111
加密数据密钥：
openstack kms datakey encrypt --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --encryption-context context  --plain-text plaintext  --datakey-plain-length 64 --sequence 11111111-1111-1111-1111-111111111111 
解密数据密钥：
openstack kms datakey decrypt --key-id 0d0466b0-e727-4d9c-b35d-f84bb474a37f --encryption-context context  --cipher-text ciphertext --datakey-cipher-length 64 --sequence 11111111-1111-1111-1111-111111111111

**Comment by IamFive** [comment]
Fixed
