### ISSUE TITLE
命令行参考查询密钥列表有误

### ISSUE THREAD

**Issue by seemebb** [Huawei/OpenStackClient_KMS#7]
3.Key list(查询密钥列表):
$ openstack volume backup ext create volume-telia-WS1 --name
A1-QianBiao-Test --description=QianBiao-Test-purpose
    --os-vb-endpoint-override=https://vbs.eu-de.otc.t-systems.com
Request Received, job id: 2c9eb2c559b8a2c2015a0e039f095821

预期：
openstack kms key list --sequence 11111111-1111-1111-1111-111111111116

**Comment by IamFive** [comment]
汗，代码只commit到本地，没push到 github上引起的。
